---
- hosts: tower01
  gather_facts: false
  connection: local

  environment:
    TOWER_USERNAME: admin
    TOWER_PASSWORD: "{{ tower_password }}"
    TOWER_HOST: https://{{ ansible_host }}

  tasks:
    # ジョブテンプレートの作成
    - name: create job template
      ansible.controller.job_template:
        name: Backup network configurations
        job_type: run
        inventory: Workshop Inventory
        project: Workshop Project
        playbook: playbooks/network_backup.yml
        execution_environment: Default execution environment
        credentials:
          - Workshop Credential
          - Controller Credential

    # ジョブテンプレートの実行
    - name: Launch a job template
      ansible.controller.job_launch:
        job_template: Backup network configurations
