---
- hosts: controller01
  gather_facts: false
  connection: local

  module_defaults:
    group/ansible.controller.controller:
      controller_host: https://{{ ansible_host }}
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"

  tasks:
    # ジョブテンプレートの作成
    - name: create job template
      ansible.controller.job_template:
        name: Backup network configurations
        job_type: run
        inventory: Workshop Inventory
        project: Workshop Project
        playbook: playbooks/network_backup.yml
        execution_environment: Default execution environment
        credentials:
          - Workshop Credential
          - Controller Credential

    # （参考） ジョブテンプレートの実行
    # - name: Launch a job template
    #   ansible.controller.job_launch:
    #     job_template: Backup network configurations
