---
- hosts: controller01
  gather_facts: false
  connection: local

  module_defaults:
    group/ansible.controller.controller:
      controller_host: https://{{ ansible_host }}
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"

  tasks:
    # ワークフロージョブテンプレートの作成
    - name: create workflow job template
      ansible.controller.workflow_job_template:
        name: Workshop Workflow
        inventory: Workshop Inventory
        organization: Default

    # ワークフロージョブテンプレートノードの作成
    # 未定義エラーを防ぐために、最後のノードから順に作成する
    # TODO: このジョブテンプレートがない
    - name: node301
      ansible.controller.workflow_job_template_node:
        identifier: node301
        workflow: Workshop Workflow
        unified_job_template: Network Automation - Restore

    - name: node201
      ansible.controller.workflow_job_template_node:
        identifier: node201
        workflow: Workshop Workflow
        unified_job_template: Network-Banner
        failure_nodes:
          - node301

    - name: node202
      ansible.controller.workflow_job_template_node:
        identifier: node202
        workflow: Workshop Workflow
        unified_job_template: Network-User
        failure_nodes:
          - node301

    - name: node101
      ansible.controller.workflow_job_template_node:
        identifier: node101
        workflow: Workshop Workflow
        unified_job_template: Backup network configurations
        success_nodes:
          - node201
          - node202

    # （参考） ジョブテンプレートの実行
    # - name: Launch a workflow job template
    #   ansible.controller.workflow_launch:
    #     workflow_template: Workshop Workflow
    #     wait: true
