---
- hosts: tower01
  gather_facts: false
  connection: local

  module_defaults:
    group/ansible.controller.controller:
      controller_host: "https://{{ ansible_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"

  tasks:
    # プロジェクトの作成
    - name: create project
      ansible.controller.project:
        name: Workshop Project
        organization: Default
        scm_type: git
        scm_url: https://github.com/ansible/workshop-examples.git
        scm_clean: true
        scm_delete_on_update: true
        scm_update_on_launch: true
        state: present

    # ジョブテンプレートの作成
    - name: create job template
      ansible.controller.job_template:
        name: Install Apache
        job_type: run
        inventory: Workshop Inventory
        project: Workshop Project
        playbook: rhel/apache/apache_install.yml
        execution_environment: Default execution environment
        credentials:
          - Workshop Credential
        limit: web
        become_enabled: true

    # （参考） ジョブテンプレートの実行
    # - name: Launch a job template
    #   ansible.controller.job_launch:
    #     wait: true
    #     job_template: Install Apache
