---
- hosts: controller01
  gather_facts: false
  connection: local

  module_defaults:
    group/ansible.controller.controller:
      controller_host: https://{{ ansible_host }}
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"

  tasks:
    # ジョブテンプレートの作成
    - name: create job template
      ansible.controller.job_template:
        name: Create index.html
        job_type: run
        inventory: Workshop Inventory
        project: Workshop Project
        playbook: rhel/apache/apache_role_install.yml
        execution_environment: Default execution environment
        credentials:
          - Workshop Credential
        limit: web
        become_enabled: true
        survey_enabled: true
        survey_spec:
          name: banner survey
          description: banner survey
          spec:
            - question_name: First Line
              question_description: First Line
              type: text
              variable: first_line
              required: false
            - question_name: Second Line
              question_description: Second Line
              type: text
              variable: second_line
              required: false

    # （参考） ジョブテンプレートの実行
    - name: Launch a job template
      ansible.controller.job_launch:
        job_template: Create index.html
        wait: true
        extra_vars:
          first_line: 111111111!!!!!!
          second_line: 222222222!!!!!!
